# SPDX-FileCopyrightText: Copyright (C) 2025 Samuel W. Flint <swflint@samuelwflint.com>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "denote-project-notes"
SPDX-PackageSupplier = "Samuel W. Flint <swflint@samuelwflint.com>"
SPDX-PackageDownloadLocation = "https://git.sr.ht/~swflint/denote-project-notes"

[[annotations]]
path = "*.el"
SPDX-FileCopyrightText = "Copyright (C) 2025 Samuel W. Flint <swflint@samuelwflint.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "*.md"
SPDX-FileCopyrightText = "Copyright (C) 2025 Samuel W. Flint <swflint@samuelwflint.com>"
SPDX-License-Identifier = "GFDL-1.3-or-later"